# config.yml
api_key_env: SIMFIN_API_KEY

data_dir: data
years: 5
market: us           # us, de, or all

# Optional toggles
datasets:
  fundamentals_quarterly: true
  fundamentals_annual: true
  prices_daily: true
  companies_meta: true
  shares_meta: true

# If true, also export 5-year trimmed CSVs to data/exports/<market>
export_last_n_years: true
